# Generated by Django 4.0.2 on 2022-02-05 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_foldertopic_documenttopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foldertopic',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='foldertopic',
            name='topic',
        ),
        migrations.DeleteModel(
            name='DocumentTopic',
        ),
        migrations.DeleteModel(
            name='FolderTopic',
        ),
    ]
