# Generated by Django 4.0.2 on 2022-02-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('topic', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
            ],
        ),
    ]
