# Generated by Django 4.0.2 on 2022-02-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_remove_foldertopic_folder_remove_foldertopic_topic_and_more'),
        ('documents', '0002_documenttopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='topics',
            field=models.ManyToManyField(through='documents.DocumentTopic', to='topics.Topic'),
        ),
    ]
