# Generated by Django 4.0.2 on 2022-02-05 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_alter_folder_created_at_alter_folder_updated_at'),
        ('documents', '0002_remove_document_topic_document_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='size',
        ),
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='folders.folder'),
        ),
    ]
