# Generated by Django 4.0.2 on 2022-02-05 21:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_remove_foldertopic_folder_remove_foldertopic_topic_and_more'),
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='topics',
            field=models.ManyToManyField(through='folders.FolderTopic', to='topics.Topic'),
        ),
        migrations.AddField(
            model_name='foldertopic',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folders.folder'),
        ),
        migrations.AddField(
            model_name='foldertopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic'),
        ),
    ]
